// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdAdxcHLhsUneY2r6HimqIpaWwTgJ9qts',
    appId: '1:374582279727:web:c081f969546ecd439fd0da',
    messagingSenderId: '374582279727',
    projectId: 'shecure-a77ed',
    authDomain: 'shecure-a77ed.firebaseapp.com',
    storageBucket: 'shecure-a77ed.appspot.com',
    measurementId: 'G-SZJDSJVHW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBe4nY9vKLMeNfZ3YZzQ28Q2_uKD02Qpk',
    appId: '1:374582279727:android:838cf7f18d4c89199fd0da',
    messagingSenderId: '374582279727',
    projectId: 'shecure-a77ed',
    storageBucket: 'shecure-a77ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTfwOY49o6vsoDyd14sf824UsWS0ys_WA',
    appId: '1:374582279727:ios:bedc30c13d7a31f79fd0da',
    messagingSenderId: '374582279727',
    projectId: 'shecure-a77ed',
    storageBucket: 'shecure-a77ed.appspot.com',
    iosBundleId: 'com.sheroes.shero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTfwOY49o6vsoDyd14sf824UsWS0ys_WA',
    appId: '1:374582279727:ios:fb78bbf763acfdb89fd0da',
    messagingSenderId: '374582279727',
    projectId: 'shecure-a77ed',
    storageBucket: 'shecure-a77ed.appspot.com',
    iosBundleId: 'com.sheroes.shero.RunnerTests',
  );
}
